version: '3.8'

services:
  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/database/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_SUPER_USER: ${POSTGRES_SUPER_USER}
      POSTGRES_SUPER_USER_PASSWORD: ${POSTGRES_SUPER_USER_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_USER_PASSWORD: ${POSTGRES_USER_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_SUPER_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - codular_network
    command: postgres

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - codular_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codular_backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      ENV: production
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_USER_PASSWORD: ${POSTGRES_USER_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_SUPER_USER: ${POSTGRES_SUPER_USER}
      POSTGRES_SUPER_USER_PASSWORD: ${POSTGRES_SUPER_USER_PASSWORD}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./.env:/app/.env:ro
    command: ["/app/wait-for-it.sh", "db:5432", "-t", "60", "--", "/app/wait-for-it.sh", "redis:6379", "-t", "60", "--", "/app/codular-backend"]
    networks:
      - codular_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  codular_network:
    driver: bridge
