basePath: /api/v1
definitions:
  response_info.ResponseInfo:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  skips.Request:
    properties:
      skipsNumber:
        minimum: 0
        type: integer
      sourceCode:
        type: string
    required:
    - skipsNumber
    - sourceCode
    type: object
  skips.Response:
    properties:
      processedCode:
        type: string
      processedCodeId:
        type: string
      responseInfo:
        $ref: '#/definitions/response_info.ResponseInfo'
    type: object
host: localhost:8082
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for the Codular project, providing functionality to generate and
    manage code skips.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Codular API
  version: "1.0"
paths:
  /skips/generate:
    post:
      consumes:
      - application/json
      description: Processes the provided source code with a specified number of skips,
        generates a unique alias, and saves it to the database.
      parameters:
      - description: Source code and number of skips
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/skips.Request'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully generated and saved skips
          schema:
            $ref: '#/definitions/skips.Response'
        "400":
          description: Invalid request or empty body
          schema:
            $ref: '#/definitions/skips.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/skips.Response'
      summary: Generate and save skips for code
      tags:
      - Skips
swagger: "2.0"
